import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import Navbar from "@/components/navbar";
import { Providers } from "@/app/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking Rooms",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Providers>
        <Navbar />
        {/* เพิ่ม padding-top เพื่อให้เนื้อหาไม่ถูกบัง และ padding-bottom สำหรับ mobile menu */}
        <main className="pt-16 pb-20 sm:pb-0">
          {children}
        </main>
      </Providers>
    </div>
  );
}